#!/bin/sh
set -e

svc_name=traefik
ns=kube-system

if [[ ! -f tls.key ]]
then
    openssl genrsa -out tls.key 2048
    openssl req -new -key tls.key -out tls.csr -subj "/CN=$svc_name.k8s.mini"

    cat >tls.ext <<EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = $svc_name.k8s.mini
DNS.2 = $svc_name
DNS.3 = $svc_name.$ns
DNS.4 = $svc_name.$ns.svc
DNS.5 = $svc_name.$ns.svc.cluster
DNS.6 = $svc_name.$ns.svc.cluster.local
EOF

    openssl x509 -req -in tls.csr -CA ../ca.crt -CAkey ../ca.key -CAcreateserial \
        -out tls.crt -days 1825 -sha256 -extfile tls.ext
fi

kubectl -n $ns delete secret traefik-ui-tls-cert || true
kubectl -n $ns create secret tls traefik-ui-tls-cert --key=tls.key --cert=tls.crt

kubectl apply -f .
