---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: arm64v8/redis:4.0
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - redis-cli ping
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - redis-cli ping
